services:
  task_manager_db:
    image: postgres:17
    container_name: task_manager_db
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "${EXTERNAL_POSTGRES_PORT}:${INTERNAL_POSTGRES_PORT}"
    volumes:
      - task_manager_postgres_data:/var/lib/postgresql/data


  task_manager:
    image: task_manager_image:latest
    build:
      context: .
    container_name: task_manager_app
    environment:
      DB_HOST: "${POSTGRES_HOST}"
      DB_PORT: "${POSTGRES_PORT}"
      DB_USER: "${POSTGRES_USER}"
      DB_PASS: "${POSTGRES_PASSWORD}"
      DB_NAME: "${POSTGRES_DB}"

      SECRET_KEY: "${SECRET_KEY}"
      ALGORITHM: "${ALGORITHM}"
    restart: always
    depends_on:
      task_manager_db:
        condition: service_healthy
    command: [ "bash", "/task_manager/docker/app.sh" ]
    ports:
      - "${EXTERNAL_APP_PORT}:${INTERNAL_APP_PORT}"

volumes:
  task_manager_postgres_data: