"""Поменял тип у колонки user_id в tasks

Revision ID: 2bfeff22d049
Revises: 0d4e51a51829
Create Date: 2025-08-21 14:49:54.477438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bfeff22d049'
down_revision: Union[str, Sequence[str], None] = '0d4e51a51829'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
